# Generated by Django 5.2.7 on 2025-11-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgb_livros', '0002_autor_alter_livro_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nome'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.RemoveField(
            model_name='autor',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='autor',
            name='biografia',
            field=models.TextField(default='', verbose_name='Biografia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidade',
            field=models.CharField(default='Não Informada', max_length=100, verbose_name='Nacionalidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome Completo'),
        ),
    ]
