# Generated by Django 5.2.5 on 2025-11-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgb_livros', '0003_alter_autor_options_remove_autor_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='link_audiobook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='plataforma_audiobook',
            field=models.CharField(blank=True, choices=[('audible', 'Audible'), ('spotify', 'Spotify'), ('youtube', 'YouTube'), ('outros', 'Outros')], max_length=50),
        ),
        migrations.AddField(
            model_name='livro',
            name='tem_audiobook',
            field=models.BooleanField(default=False),
        ),
    ]
