# Generated by Django 5.2.5 on 2025-11-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgb_livros', '0004_autor_data_nascimento_livro_link_audiobook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['titulo'], 'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AddField(
            model_name='livro',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, null=True, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='link_audiobook',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Audiobook'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='plataforma_audiobook',
            field=models.CharField(blank=True, choices=[('audible', 'Audible'), ('spotify', 'Spotify'), ('ubook', 'Ubook'), ('storytel', 'Storytel'), ('youtube', 'YouTube'), ('outros', 'Outros')], max_length=50, null=True, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='tem_audiobook',
            field=models.BooleanField(default=False, verbose_name='Tem Audiobook?'),
        ),
    ]
